# Permalinks
permalink:           pretty

# Setup
title:               J.T. Baker Jr.
tagline:             A Fun Data Science Blog For Everyone (But Mostly Me)
url:                 http://JTBake490.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Baker Jr.
  url:               
  email:             jrbake490@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/JTBake490

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
